import { DatabaseSync } from 'node:sqlite';
import path from 'path';
import fs from 'fs';

const DB_PATH = path.join(process.cwd(), 'data', 'tracker.db');

const dataDir = path.dirname(DB_PATH);
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

let _db: DatabaseSync | null = null;

export function getDb(): DatabaseSync {
  if (_db) return _db;
  _db = new DatabaseSync(DB_PATH);
  _db.exec('PRAGMA journal_mode = WAL');
  _db.exec('PRAGMA foreign_keys = ON');
  initSchema(_db);
  return _db;
}

function initSchema(db: DatabaseSync) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS sites (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      lat REAL NOT NULL,
      lng REAL NOT NULL,
      type TEXT NOT NULL DEFAULT 'greenfield',
      status TEXT NOT NULL DEFAULT 'available',
      power_capacity_mw REAL DEFAULT 0,
      power_available_mw REAL DEFAULT 0,
      land_acres REAL DEFAULT 0,
      fiber_access TEXT DEFAULT 'none',
      water_access TEXT DEFAULT 'none',
      opportunity_score INTEGER DEFAULT 50,
      region TEXT,
      country TEXT,
      state TEXT,
      city TEXT,
      power_cost_per_mwh REAL DEFAULT 60,
      pue_estimate REAL DEFAULT 1.4,
      asking_price_musd REAL,
      notes TEXT DEFAULT '',
      tags TEXT DEFAULT '[]',
      user_notes TEXT DEFAULT '',
      watchlisted INTEGER DEFAULT 0,
      last_updated TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS signals (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
      type TEXT NOT NULL,
      date TEXT,
      description TEXT,
      source_url TEXT,
      confidence TEXT DEFAULT 'medium',
      auto_generated INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS ingestion_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      script TEXT NOT NULL,
      status TEXT DEFAULT 'running',
      started_at TEXT DEFAULT (datetime('now')),
      completed_at TEXT,
      signals_found INTEGER DEFAULT 0,
      output TEXT DEFAULT ''
    );

    CREATE INDEX IF NOT EXISTS idx_signals_site ON signals(site_id);
    CREATE INDEX IF NOT EXISTS idx_sites_score ON sites(opportunity_score DESC);
    CREATE INDEX IF NOT EXISTS idx_sites_region ON sites(region);
    CREATE INDEX IF NOT EXISTS idx_sites_country ON sites(country);
  `);

  // Migrations for new columns (safe to run repeatedly — catches error if column exists)
  try { db.exec(`ALTER TABLE sites ADD COLUMN owner TEXT DEFAULT ''`); } catch {}
  try { db.exec(`ALTER TABLE sites ADD COLUMN for_sale_probability INTEGER DEFAULT 50`); } catch {}
}

// ── Site queries ─────────────────────────────────────────────────────
export function getAllSites(db: DatabaseSync) {
  const sites = db.prepare(`SELECT * FROM sites ORDER BY opportunity_score DESC`).all() as any[];
  const signals = db.prepare(`SELECT * FROM signals ORDER BY date DESC`).all() as any[];
  const sigMap: Record<string, any[]> = {};
  for (const s of signals) {
    if (!sigMap[s.site_id]) sigMap[s.site_id] = [];
    sigMap[s.site_id].push(mapSignal(s));
  }
  return sites.map(s => ({ ...mapSite(s), signals: sigMap[s.id] || [] }));
}

export function getSiteById(db: DatabaseSync, id: string) {
  const site = db.prepare(`SELECT * FROM sites WHERE id = ?`).get(id) as any;
  if (!site) return null;
  const signals = db.prepare(`SELECT * FROM signals WHERE site_id = ? ORDER BY date DESC`).all(id) as any[];
  return { ...mapSite(site), signals: signals.map(mapSignal) };
}

export function updateSite(db: DatabaseSync, id: string, updates: Partial<any>) {
  const fields = Object.keys(updates).map(k => `${toSnake(k)} = ?`).join(', ');
  const values = Object.values(updates);
  db.prepare(`UPDATE sites SET ${fields}, last_updated = datetime('now') WHERE id = ?`).run(...values, id);
  return getSiteById(db, id);
}

export function addSignal(db: DatabaseSync, signal: any) {
  return db.prepare(`
    INSERT INTO signals (site_id, type, date, description, source_url, confidence, auto_generated)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `).run(signal.siteId, signal.type, signal.date, signal.description, signal.sourceUrl || null, signal.confidence || 'medium', signal.autoGenerated ? 1 : 0);
}

export function getIngestionLog(db: DatabaseSync, limit = 20) {
  return db.prepare(`SELECT * FROM ingestion_log ORDER BY started_at DESC LIMIT ?`).all(limit);
}

export function logIngestionStart(db: DatabaseSync, script: string): number {
  const result = db.prepare(`INSERT INTO ingestion_log (script, status) VALUES (?, 'running')`).run(script);
  return result.lastInsertRowid as number;
}

export function logIngestionComplete(db: DatabaseSync, id: number, signalsFound: number, output: string, status = 'completed') {
  db.prepare(`UPDATE ingestion_log SET status = ?, completed_at = datetime('now'), signals_found = ?, output = ? WHERE id = ?`)
    .run(status, signalsFound, output, id);
}

// ── Helpers ──────────────────────────────────────────────────────────
function mapSite(row: any) {
  return {
    id: row.id,
    name: row.name,
    lat: row.lat,
    lng: row.lng,
    type: row.type,
    status: row.status,
    powerCapacityMW: row.power_capacity_mw,
    powerAvailableMW: row.power_available_mw,
    landAcres: row.land_acres,
    fiberAccess: row.fiber_access,
    waterAccess: row.water_access,
    opportunityScore: row.opportunity_score,
    region: row.region,
    country: row.country,
    state: row.state,
    city: row.city,
    powerCostPerMWh: row.power_cost_per_mwh,
    pueEstimate: row.pue_estimate,
    askingPriceMUSD: row.asking_price_musd,
    notes: row.notes,
    tags: JSON.parse(row.tags || '[]'),
    owner: row.owner || '',
    forSaleProbability: row.for_sale_probability ?? 50,
    userNotes: row.user_notes,
    watchlisted: row.watchlisted === 1,
    lastUpdated: row.last_updated,
    createdAt: row.created_at,
  };
}

function mapSignal(row: any) {
  return {
    id: row.id,
    siteId: row.site_id,
    type: row.type,
    date: row.date,
    description: row.description,
    sourceUrl: row.source_url,
    confidence: row.confidence,
    autoGenerated: row.auto_generated === 1,
    createdAt: row.created_at,
  };
}

function toSnake(camel: string) {
  return camel.replace(/([A-Z])/g, '_$1').toLowerCase();
}
