import { DatabaseSync } from 'node:sqlite';

interface SiteRow {
  id: string; name: string; lat: number; lng: number;
  type: string; status: string; powerCapacityMW: number; powerAvailableMW: number;
  landAcres: number; fiberAccess: string; waterAccess: string;
  opportunityScore: number; region: string; country: string; state: string; city: string;
  powerCostPerMWh: number; pueEstimate: number; notes: string; tags: string[];
  owner?: string; forSaleProbability?: number;
  signals: { type: string; date: string; desc: string; confidence: string }[];
}

const SITES: SiteRow[] = [
  // ══ US: NORTHEAST / MID-ATLANTIC ════════════════════════════════
  { id:'pwc-va', name:'Prince William Digital Gateway, VA', lat:38.6849, lng:-77.5267,
    type:'greenfield', status:'under_construction', powerCapacityMW:2000, powerAvailableMW:1400, landAcres:5000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:93,
    region:'northeast', country:'US', state:'VA', city:'Gainesville',
    powerCostPerMWh:55, pueEstimate:1.4,
    notes:'Largest entitled DC district in the US. 5,000+ acres approved. Dominion building 800MW substations. Multiple tier-1 operators committed. Still significant land at $500k–$1.5M/acre. The post-Ashburn frontier for NOVA.',
    tags:['tax_incentives','dc_friendly_zoning','dominion_power','tier1_market','fastest_growing'],
    signals:[
      {type:'zoning_change',date:'2023-11-15',desc:'PWC Board approves 5,000+ acre Data Center Overlay District',confidence:'high'},
      {type:'interconnection_request',date:'2024-03-22',desc:'Dominion Energy files 800MW substation upgrade for PWC corridor',confidence:'high'},
      {type:'building_permit',date:'2024-08-10',desc:'12 DC permits issued Q2-Q3 2024 totaling $4.2B construction value',confidence:'high'},
      {type:'news',date:'2025-01-14',desc:'QTS, Vantage, Digital Realty all announce PWC expansions',confidence:'high'},
    ]},
  { id:'loudoun-va', name:'Loudoun County / Ashburn — Data Center Alley, VA', lat:39.0438, lng:-77.4874,
    type:'existing_dc', status:'operational', powerCapacityMW:5500, powerAvailableMW:250, landAcres:150,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:74,
    region:'northeast', country:'US', state:'VA', city:'Ashburn',
    powerCostPerMWh:60, pueEstimate:1.45,
    notes:'World\'s densest DC market. Land at $2M+/acre. Best play: acquire existing Equinix/Digital Realty facilities or vacant parcels in Brambleton/One Loudoun corridor. MAE-East fiber hub = best East Coast connectivity.',
    tags:['land_constrained','tier1_market','premium_fiber','acquisition_target','dominion_power'],
    signals:[
      {type:'land_sale',date:'2024-07-12',desc:'Last 50-acre undeveloped Ashburn parcel sold for $2.1M/acre',confidence:'high'},
      {type:'news',date:'2024-10-01',desc:'Equinix DC14-DC16 expansion — $1.2B announced',confidence:'high'},
    ]},
  { id:'stafford-va', name:'Stafford / Fredericksburg Corridor, VA', lat:38.3032, lng:-77.4605,
    type:'greenfield', status:'emerging', powerCapacityMW:600, powerAvailableMW:500, landAcres:2000,
    fiberAccess:'single', waterAccess:'limited', opportunityScore:79,
    region:'northeast', country:'US', state:'VA', city:'Stafford',
    powerCostPerMWh:55, pueEstimate:1.4,
    notes:'Next market south of PWC on I-95. Land $100k–$300k/acre. Dominion extending transmission south. 45-min from NOVA. Still early — first-mover advantage significant.',
    tags:['tax_incentives','dominion_power','emerging_market','land_available'],
    signals:[
      {type:'zoning_change',date:'2024-09-20',desc:'Stafford County proposes industrial-tech zoning overlay for I-95 corridor',confidence:'medium'},
      {type:'news',date:'2025-02-10',desc:'Dominion Energy announces transmission upgrade to Stafford substation',confidence:'high'},
    ]},
  { id:'richmond-va', name:'Richmond Metro / Henrico County, VA', lat:37.5407, lng:-77.4360,
    type:'greenfield', status:'emerging', powerCapacityMW:400, powerAvailableMW:350, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:78,
    region:'northeast', country:'US', state:'VA', city:'Richmond',
    powerCostPerMWh:52, pueEstimate:1.38,
    notes:'Strong fiber hub (Zayo, Lumen, Cox). James River water access. Land $100k–$250k/acre. QTS built large campus here. Dominion HQ city — utility relationship advantage. Growing enterprise demand from DC overflow.',
    tags:['tax_incentives','dominion_power','fiber_hub','water_abundant'],
    signals:[
      {type:'building_permit',date:'2024-11-05',desc:'QTS Richmond Phase 3 permit filed — 200MW expansion',confidence:'high'},
      {type:'interconnection_request',date:'2025-01-18',desc:'Dominion files 300MW substation upgrade Henrico County',confidence:'high'},
    ]},
  { id:'plattsburgh-ny', name:'Plattsburgh, NY — NYPA Hydro Zone', lat:44.6995, lng:-73.4529,
    type:'greenfield', status:'available', powerCapacityMW:300, powerAvailableMW:250, landAcres:1000,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:80,
    region:'northeast', country:'US', state:'NY', city:'Plattsburgh',
    powerCostPerMWh:32, pueEstimate:1.3,
    notes:'NYPA hydro from St. Lawrence/Niagara — cheapest power in northeast US ($0.032/MWh). Lake Champlain water cooling. Cold climate = free cooling 9 months. 2 hours from Montreal. Land $30k–$100k/acre. Fiber needs upgrade — primary constraint.',
    tags:['nypa_hydro','cheapest_northeast_power','water_abundant','free_cooling','fiber_investment_needed'],
    signals:[
      {type:'interconnection_request',date:'2024-08-30',desc:'NYPA files Plattsburgh industrial power program — 200MW industrial reserve rate',confidence:'high'},
    ]},
  { id:'rtp-nc', name:'Raleigh-Durham / Research Triangle Park, NC', lat:35.9048, lng:-78.9468,
    type:'greenfield', status:'emerging', powerCapacityMW:500, powerAvailableMW:400, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:79,
    region:'northeast', country:'US', state:'NC', city:'Research Triangle Park',
    powerCostPerMWh:50, pueEstimate:1.4,
    notes:'Duke Energy territory + world-class fiber. Apple $1B campus, Meta Apex NC site. Jordan Lake water. Land $100k–$300k/acre in outer RTP. Duke aggressive renewable buildout. UNC/NCSU/Duke research = latency-sensitive demand.',
    tags:['duke_energy','research_park','apple_adjacent','meta_adjacent','water_abundant'],
    signals:[
      {type:'building_permit',date:'2024-09-15',desc:'Meta Apex NC campus Phase 2 permit — 300MW expansion',confidence:'high'},
    ]},

  // ══ US: SOUTHEAST ════════════════════════════════════════════════
  { id:'new-albany-oh', name:'New Albany Technology Campus, OH', lat:40.0814, lng:-82.7924,
    type:'greenfield', status:'under_construction', powerCapacityMW:3500, powerAvailableMW:2000, landAcres:4500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:95,
    region:'midwest', country:'US', state:'OH', city:'New Albany',
    powerCostPerMWh:45, pueEstimate:1.35,
    notes:'#1 US greenfield market 2024-2025. Google 500MW campus, Amazon $7.8B campus, Meta 2M sqft, Microsoft all under construction. AEP Ohio building 3 new 345kV substations. Intel fab in Licking County = massive transmission infrastructure. Land $200k–$600k/acre. 40% cheaper power than NOVA.',
    tags:['fastest_growing','tax_incentives','aep_ohio','intel_adjacent','dc_friendly_zoning','tier1_market'],
    signals:[
      {type:'interconnection_request',date:'2024-02-14',desc:'AEP Ohio files 3 new 345kV substations in Licking/Delaware County',confidence:'high'},
      {type:'building_permit',date:'2024-05-30',desc:'New Albany approves 6 additional DC permits on Technology Campus',confidence:'high'},
      {type:'news',date:'2024-08-22',desc:'Amazon $7.8B Columbus campus — largest US DC investment announced',confidence:'high'},
      {type:'job_posting',date:'2024-11-01',desc:'1,200+ DC tech jobs posted Columbus metro in 30-day period',confidence:'high'},
    ]},
  { id:'memphis-tn', name:'Memphis / DeSoto County Metro, TN/MS', lat:34.9958, lng:-89.9820,
    type:'greenfield', status:'under_construction', powerCapacityMW:2000, powerAvailableMW:1500, landAcres:5000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:89,
    region:'southeast', country:'US', state:'TN', city:'Memphis',
    powerCostPerMWh:38, pueEstimate:1.4,
    notes:'xAI Colossus (150MW, 100k H100/H200) anchoring market. TVA power is among cheapest in US ($38/MWh avg). Mississippi River water cooling. Rail access. Land $30k–$100k/acre in DeSoto County. MASSIVE AI datacenter buildout underway — hyperscalers following xAI.',
    tags:['xai_anchor','tva_power','cheapest_power','ai_compute','water_abundant','land_abundant'],
    signals:[
      {type:'partner_announcement',date:'2024-07-22',desc:'xAI Colossus goes live — 100,000 H100 GPUs, 150MW Memphis campus',confidence:'high'},
      {type:'interconnection_request',date:'2024-10-15',desc:'TVA approves 1,000MW capacity reservation for Memphis industrial corridor',confidence:'high'},
      {type:'news',date:'2025-01-08',desc:'Two hyperscalers reported acquiring 500+ acre DeSoto County parcels',confidence:'medium'},
    ]},
  { id:'clarksville-tn', name:'Clarksville / Montgomery County, TN', lat:36.5298, lng:-87.3595,
    type:'greenfield', status:'under_construction', powerCapacityMW:800, powerAvailableMW:500, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:82,
    region:'southeast', country:'US', state:'TN', city:'Clarksville',
    powerCostPerMWh:40, pueEstimate:1.38,
    notes:'Google building 400MW campus. TVA anchor. Cumberland River. Tennessee tax incentives. Adjacent land at $50k–$150k/acre. Fort Campbell infrastructure supports reliable power.',
    tags:['google_campus','tva_power','tax_incentives','water_abundant'],
    signals:[
      {type:'building_permit',date:'2024-03-12',desc:'Google Clarksville campus Phase 2 permit — 200MW additional',confidence:'high'},
    ]},
  { id:'smyrna-tn', name:'Smyrna / Murfreesboro, TN', lat:35.9823, lng:-86.5186,
    type:'greenfield', status:'available', powerCapacityMW:500, powerAvailableMW:450, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:80,
    region:'southeast', country:'US', state:'TN', city:'Smyrna',
    powerCostPerMWh:40, pueEstimate:1.38,
    notes:'TVA power. I-24 corridor southeast of Nashville. Stones River water. Land $50k–$150k/acre. Nissan North America HQ = major industrial power infrastructure. Amazon logistics hub = fiber infrastructure. Tennessee no state income tax.',
    tags:['tva_power','water_abundant','tax_incentives','land_available'],
    signals:[
      {type:'news',date:'2025-02-20',desc:'TVA announces Smyrna area as priority industrial power zone — 400MW reserved',confidence:'medium'},
    ]},
  { id:'huntsville-al', name:'Huntsville / Madison County, AL', lat:34.6590, lng:-86.7710,
    type:'greenfield', status:'emerging', powerCapacityMW:500, powerAvailableMW:450, landAcres:2500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:81,
    region:'southeast', country:'US', state:'AL', city:'Huntsville',
    powerCostPerMWh:38, pueEstimate:1.4,
    notes:'TVA power — same cheap rate as Memphis. NASA Marshall + DoD = defense tech demand. Redstone Arsenal adjacency. Land $40k–$120k/acre. Tennessee River (Wheeler Lake) water. Alabama $0 corporate income tax for DCs. Boeing, Northrop, Lockheed = enterprise demand. Hidden gem.',
    tags:['tva_power','cheapest_power','defense_tech','water_abundant','no_corporate_tax','nasa_adjacent'],
    signals:[
      {type:'news',date:'2025-01-25',desc:'Alabama enacts strongest DC tax incentive law — 20-year property tax exemption',confidence:'high'},
    ]},
  { id:'atlanta-douglas-ga', name:'Atlanta / Douglas County, GA', lat:33.6887, lng:-84.7527,
    type:'greenfield', status:'available', powerCapacityMW:600, powerAvailableMW:500, landAcres:2500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:81,
    region:'southeast', country:'US', state:'GA', city:'Douglasville',
    powerCostPerMWh:52, pueEstimate:1.42,
    notes:'Atlanta metro expansion corridor. Georgia Power (Southern Co.) territory with capacity. Land $80k–$200k/acre. Switch, Aligned, QTS all Atlanta metro presences. State of Georgia excellent DC tax incentives.',
    tags:['georgia_power','tax_incentives','airport_adjacent','land_available'],
    signals:[
      {type:'zoning_change',date:'2024-05-10',desc:'Douglas County approves 1,500 acre tech industrial zone on I-20 corridor',confidence:'high'},
    ]},
  { id:'indianapolis-in', name:'Indianapolis / Avon, IN', lat:39.7684, lng:-86.3953,
    type:'greenfield', status:'emerging', powerCapacityMW:400, powerAvailableMW:350, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:76,
    region:'midwest', country:'US', state:'IN', city:'Avon',
    powerCostPerMWh:48, pueEstimate:1.38,
    notes:'IPL + Duke Indiana. Indiana DC incentive law (2023) — 10-year personal property tax exemption. I-70/I-74 fiber. Eagle Creek Reservoir water. Land $50k–$150k/acre. Central US latency advantage. Emerging alternative to Columbus OH.',
    tags:['ipl_power','indiana_incentives','water_abundant','central_latency','emerging_midwest'],
    signals:[
      {type:'news',date:'2024-11-01',desc:'Indiana passes data center tax incentive bill — 10-year personal property tax exemption',confidence:'high'},
    ]},

  // ══ US: MIDWEST ══════════════════════════════════════════════════
  { id:'aurora-il', name:'Chicago / Aurora & Elk Grove, IL', lat:41.7606, lng:-88.3201,
    type:'existing_dc', status:'operational', powerCapacityMW:2000, powerAvailableMW:400, landAcres:300,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:83,
    region:'midwest', country:'US', state:'IL', city:'Aurora',
    powerCostPerMWh:55, pueEstimate:1.42,
    notes:'3rd largest US DC market. Midwest carrier hotel via 350 E. Cermak. ComEd (Exelon) nuclear power. Equinix CH1-CH8, Flexential, Lumen all present. Land available in Aurora/Elk Grove for expansion.',
    tags:['tier2_market','nuclear_power','fiber_hub','great_lakes_water','comEd'],
    signals:[
      {type:'news',date:'2024-11-20',desc:'ComEd announces $2.5B grid upgrade including Aurora substation expansion',confidence:'high'},
    ]},
  { id:'dekalb-il', name:'DeKalb, IL — Meta Campus Zone', lat:41.9297, lng:-88.7504,
    type:'greenfield', status:'under_construction', powerCapacityMW:1500, powerAvailableMW:800, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:84,
    region:'midwest', country:'US', state:'IL', city:'DeKalb',
    powerCostPerMWh:52, pueEstimate:1.38,
    notes:'Meta 2,500+ acre campus under construction ($800M+). Adjacent land at $50k–$150k/acre. ComEd building dedicated substation. Wind farm proximity for renewable PPA.',
    tags:['meta_campus','comEd','tax_incentives','wind_renewable','land_adjacent'],
    signals:[
      {type:'building_permit',date:'2024-01-25',desc:'Meta DeKalb Phase 2 — 600MW addition permit filed',confidence:'high'},
    ]},
  { id:'waukee-ia', name:'Des Moines / Waukee, IA', lat:41.6005, lng:-93.8091,
    type:'greenfield', status:'under_construction', powerCapacityMW:2000, powerAvailableMW:1000, landAcres:3000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:85,
    region:'midwest', country:'US', state:'IA', city:'Waukee',
    powerCostPerMWh:42, pueEstimate:1.35,
    notes:'Apple (520MW campus), Microsoft (3 campuses), Google all major presences. MidAmerican Energy (Berkshire Hathaway) — 100% renewable wind. Iowa NO state income tax for DCs. Land $60k–$180k/acre. Raccoon River water. Top-tier underappreciated market.',
    tags:['apple_campus','microsoft_campus','google_campus','midamerican_energy','100pct_renewable','no_state_tax'],
    signals:[
      {type:'news',date:'2024-07-18',desc:'Microsoft announces 3rd Iowa campus — $3.3B investment',confidence:'high'},
      {type:'building_permit',date:'2025-02-14',desc:'Apple Waukee Phase 4 permit — $1.2B expansion',confidence:'high'},
    ]},
  { id:'eagan-mn', name:'Minneapolis / Eagan, MN', lat:44.8045, lng:-93.1667,
    type:'existing_dc', status:'operational', powerCapacityMW:500, powerAvailableMW:200, landAcres:300,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:78,
    region:'midwest', country:'US', state:'MN', city:'Eagan',
    powerCostPerMWh:52, pueEstimate:1.35,
    notes:'Minnesota cold climate = free cooling 8 months/year. Xcel Energy + Great River Energy. Mississippi River basin. MAPS3 fiber hub. Flexential, CBRE, Tier 1 capital all MN present. Land $150k–$350k/acre.',
    tags:['xcel_energy','free_cooling','great_lakes_water','fiber_hub','climate_advantage'],
    signals:[
      {type:'news',date:'2024-08-20',desc:'Xcel Energy Minnesota announces 1GW renewable buildout 2024-2027',confidence:'high'},
    ]},
  { id:'kansas-city-mo', name:'Kansas City / Lee\'s Summit, MO', lat:38.9028, lng:-94.2820,
    type:'greenfield', status:'emerging', powerCapacityMW:400, powerAvailableMW:350, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:76,
    region:'midwest', country:'US', state:'MO', city:"Lee's Summit",
    powerCostPerMWh:46, pueEstimate:1.38,
    notes:'Kansas City Power & Light (Evergy). Missouri River + Lake of Ozarks. Fiber-rich (CenturyLink/Lumen major hub). Land $50k–$150k/acre. Midwest centrality = low latency to both coasts.',
    tags:['evergy_power','water_abundant','fiber_hub','midcontinent_latency','emerging_market'],
    signals:[
      {type:'zoning_change',date:'2024-07-12',desc:"Lee's Summit approves 600-acre tech industrial zone near I-70 corridor",confidence:'high'},
    ]},
  { id:'stlouis-mo', name:'St. Louis / Chesterfield, MO', lat:38.6605, lng:-90.5776,
    type:'greenfield', status:'emerging', powerCapacityMW:400, powerAvailableMW:350, landAcres:1000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:75,
    region:'midwest', country:'US', state:'MO', city:'Chesterfield',
    powerCostPerMWh:46, pueEstimate:1.4,
    notes:'Ameren Missouri territory. Mississippi River water. I-70/I-64 fiber. Land $60k–$180k/acre. Centene, Boeing, Edward Jones enterprise demand. Midwest centrality latency sweet spot.',
    tags:['ameren_power','mississippi_river','fiber_hub','financial_enterprise','emerging_midwest'],
    signals:[
      {type:'news',date:'2024-08-14',desc:'Ameren Missouri announces 600MW renewable expansion — industrial tariff focus',confidence:'high'},
    ]},

  // ══ US: TEXAS / SOUTHWEST ════════════════════════════════════════
  { id:'allen-tx', name:'Allen / McKinney / Plano, TX (DFW North)', lat:33.1151, lng:-96.6752,
    type:'greenfield', status:'available', powerCapacityMW:800, powerAvailableMW:500, landAcres:800,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:84,
    region:'southwest', country:'US', state:'TX', city:'Allen',
    powerCostPerMWh:48, pueEstimate:1.45,
    notes:'Oncor territory — ERCOT grid, no federal FERC = faster permitting. Frontier fiber + multiple carriers. Land $200k–$500k/acre. CyrusOne, Equinix, QTS all present.',
    tags:['oncor_ercot','fiber_hub','airport_adjacent','tax_incentives','ercot_grid'],
    signals:[
      {type:'interconnection_request',date:'2024-05-22',desc:'Oncor files 400MW substation upgrade Collin County north corridor',confidence:'high'},
    ]},
  { id:'san-antonio-tx', name:'San Antonio / Bexar County, TX', lat:29.4241, lng:-98.4936,
    type:'greenfield', status:'under_construction', powerCapacityMW:1500, powerAvailableMW:1000, landAcres:4000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:88,
    region:'southwest', country:'US', state:'TX', city:'San Antonio',
    powerCostPerMWh:44, pueEstimate:1.42,
    notes:'Microsoft 3 massive campuses, Google, Apple all building. CPS Energy (city-owned) = best utility relationship in Texas. Land $50k–$200k/acre in outer corridors. Texas Enterprise Zone = 10-year tax abatement. Underpriced vs. DFW.',
    tags:['microsoft_anchor','cps_energy','ercot_grid','tax_incentives','land_abundant'],
    signals:[
      {type:'building_permit',date:'2024-02-20',desc:'Microsoft Phase 4 SA campus — 500MW expansion',confidence:'high'},
      {type:'partner_announcement',date:'2024-08-15',desc:'CPS Energy announces dedicated DC power program — 2GW reserved',confidence:'high'},
    ]},
  { id:'oklahoma-city-ok', name:'Oklahoma City, OK', lat:35.5646, lng:-97.6147,
    type:'greenfield', status:'emerging', powerCapacityMW:600, powerAvailableMW:550, landAcres:3000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:78,
    region:'southwest', country:'US', state:'OK', city:'Oklahoma City',
    powerCostPerMWh:42, pueEstimate:1.42,
    notes:'OGE Energy + wind power. Oklahoma 35%+ wind penetration = cheap renewable PPAs. Land $20k–$80k/acre. ERCOT-adjacent on southern Oklahoma border. I-40 fiber corridor. OKC tax incentives. Tornado/hail risk = hardened construction required.',
    tags:['wind_renewable','cheap_power','oge_energy','land_abundant','tornado_risk'],
    signals:[
      {type:'interconnection_request',date:'2024-11-05',desc:'OGE Energy 300MW wind interconnection for central Oklahoma industrial tariff',confidence:'high'},
    ]},

  // ══ US: MOUNTAIN WEST ════════════════════════════════════════════
  { id:'cheyenne-wy', name:'Cheyenne / Laramie County, WY', lat:41.1400, lng:-104.8202,
    type:'greenfield', status:'under_construction', powerCapacityMW:1200, powerAvailableMW:800, landAcres:5000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:87,
    region:'mountain', country:'US', state:'WY', city:'Cheyenne',
    powerCostPerMWh:42, pueEstimate:1.35,
    notes:'Microsoft (3 campuses), Google, Switch all built. Wyoming: NO state income/corporate tax, NO sales tax on DC equipment. Rocky Mountain Power (PacifiCorp). Elevation = free cooling 80% of year. Land $20k–$80k/acre. Best incentives in US.',
    tags:['no_state_tax','microsoft_anchor','google_campus','pacificorp','free_cooling','best_incentives'],
    signals:[
      {type:'news',date:'2024-04-10',desc:'Microsoft announces Cheyenne Phase 3 — $500M additional',confidence:'high'},
      {type:'zoning_change',date:'2025-01-05',desc:'Wyoming passes SB-27 extending DC tax exemption through 2035',confidence:'high'},
    ]},
  { id:'denver-co', name:'Denver / Centennial, CO', lat:39.5807, lng:-104.8772,
    type:'greenfield', status:'available', powerCapacityMW:600, powerAvailableMW:450, landAcres:1200,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:79,
    region:'mountain', country:'US', state:'CO', city:'Centennial',
    powerCostPerMWh:58, pueEstimate:1.35,
    notes:'Xcel Energy. E-470/DIA corridor east is the growth zone. Mile-high altitude = free cooling 8+ months. South Platte River. Land $100k–$300k/acre. Google, Twitter/X, CenturyLink all CO presence.',
    tags:['xcel_energy','airport_adjacent','free_cooling','emerging_market'],
    signals:[
      {type:'news',date:'2024-10-15',desc:'Xcel Energy Colorado announces 500MW industrial load expansion program',confidence:'high'},
    ]},
  { id:'bluffdale-ut', name:'Salt Lake City / Bluffdale, UT', lat:40.4889, lng:-111.9278,
    type:'existing_dc', status:'operational', powerCapacityMW:600, powerAvailableMW:200, landAcres:400,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:77,
    region:'mountain', country:'US', state:'UT', city:'Bluffdale',
    powerCostPerMWh:50, pueEstimate:1.38,
    notes:'NSA Utah Data Center anchors market. eBay, Adobe, Overstock, Switch present. Rocky Mountain Power. Jordan River water (limited). Market maturing — watch for acquisition targets.',
    tags:['nsa_anchor','pacificorp','acquisition_target','fiber_hub'],
    signals:[
      {type:'news',date:'2024-12-05',desc:'Switch acquires 200-acre Bluffdale parcel for Phase 2 expansion',confidence:'high'},
    ]},
  { id:'lehi-ut', name:'Lehi / Provo — Silicon Slopes, UT', lat:40.3916, lng:-111.8508,
    type:'greenfield', status:'available', powerCapacityMW:400, powerAvailableMW:300, landAcres:800,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:78,
    region:'mountain', country:'US', state:'UT', city:'Lehi',
    powerCostPerMWh:50, pueEstimate:1.35,
    notes:'Utah tech hub. Oracle, Vivint, Adobe, Qualtrics HQ nearby = enterprise demand. Rocky Mountain Power. I-15 fiber. Adjacent to NSA campus. Cold winters. Enterprise/colocation focus.',
    tags:['pacificorp','tech_hub','oracle_adjacent','enterprise_demand'],
    signals:[
      {type:'news',date:'2024-11-12',desc:'QTS announces Lehi campus — 200MW Phase 1 targeting enterprise colo',confidence:'high'},
    ]},
  { id:'boise-id', name:'Boise / Nampa, ID', lat:43.6150, lng:-116.2023,
    type:'greenfield', status:'emerging', powerCapacityMW:600, powerAvailableMW:500, landAcres:3000,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:81,
    region:'mountain', country:'US', state:'ID', city:'Nampa',
    powerCostPerMWh:35, pueEstimate:1.32,
    notes:'Idaho Power hydro — cheapest power in US ($0.035/kWh). Snake River water. Treasure Valley land $40k–$120k/acre. Micron semiconductor fab = power infrastructure investment. Cold winters = free cooling.',
    tags:['cheapest_power','hydro_power','water_abundant','free_cooling','micron_adjacent'],
    signals:[
      {type:'news',date:'2025-02-05',desc:'Sabey Data Centers acquires 400-acre Nampa greenfield site',confidence:'high'},
    ]},
  { id:'reno-nv', name:'Reno / Sparks, NV', lat:39.5296, lng:-119.8138,
    type:'existing_dc', status:'operational', powerCapacityMW:800, powerAvailableMW:300, landAcres:500,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:78,
    region:'mountain', country:'US', state:'NV', city:'Reno',
    powerCostPerMWh:50, pueEstimate:1.38,
    notes:'Switch TAHOE RENO 1, Apple, Google, Microsoft all present. NV Energy. Nevada no state income tax. Truckee River water limited. Market maturing — $200k–$500k/acre.',
    tags:['switch_campus','nv_energy','no_state_tax','acquisition_target'],
    signals:[
      {type:'news',date:'2024-08-30',desc:'Switch Reno Phase 9 — 200MW addition announced',confidence:'high'},
    ]},
  { id:'henderson-nv', name:'Las Vegas / Henderson — Switch SUPERNAP, NV', lat:36.0395, lng:-114.9817,
    type:'existing_dc', status:'operational', powerCapacityMW:1800, powerAvailableMW:300, landAcres:500,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:77,
    region:'mountain', country:'US', state:'NV', city:'Henderson',
    powerCostPerMWh:52, pueEstimate:1.48,
    notes:'Switch SUPERNAP — 7M sqft potential. NV Energy. No state income tax. Colorado River (Lake Mead) water risk. Hot climate OPEX premium. DigitalBridge-owned since 2022 — watch for JV/divestiture opportunities.',
    tags:['switch_campus','nv_energy','no_state_tax','water_scarcity_risk','acquisition_target'],
    signals:[
      {type:'news',date:'2025-01-10',desc:'DigitalBridge explores Switch SUPERNAP east campus JV with hyperscaler',confidence:'medium'},
    ]},
  { id:'tucson-az', name:'Tucson, AZ', lat:32.2226, lng:-110.9747,
    type:'greenfield', status:'emerging', powerCapacityMW:400, powerAvailableMW:350, landAcres:2000,
    fiberAccess:'single', waterAccess:'limited', opportunityScore:74,
    region:'mountain', country:'US', state:'AZ', city:'Tucson',
    powerCostPerMWh:55, pueEstimate:1.48,
    notes:'TEP (Tucson Electric Power). University of Arizona proximity = research demand. Land $50k–$150k/acre — much cheaper than Phoenix. Arizona solar PPA cheap. Boeing + Raytheon defense = enterprise demand.',
    tags:['tep_power','solar_ppa','land_available','water_scarcity_risk','defense_enterprise'],
    signals:[
      {type:'zoning_change',date:'2025-01-08',desc:'Tucson approves 500-acre Kino Tech Park expansion for industrial tech use',confidence:'high'},
    ]},

  // ══ US: PACIFIC / NORTHWEST ══════════════════════════════════════
  { id:'george-wa', name:'George / Mattawa, WA — Columbia Basin', lat:47.0854, lng:-119.8700,
    type:'greenfield', status:'available', powerCapacityMW:2000, powerAvailableMW:1500, landAcres:10000,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:87,
    region:'northwest', country:'US', state:'WA', city:'George',
    powerCostPerMWh:28, pueEstimate:1.3,
    notes:'Grant County PUD hydro — CHEAPEST in US ($0.025-0.030/kWh). Adjacent to Quincy but MORE LAND at LOWER prices ($10k–$50k/acre). Columbia River water. Cold climate = free cooling 9 months. Quincy is nearly full — this is the natural expansion. Fiber single route — key investment needed.',
    tags:['cheapest_power','hydro_power','water_abundant','free_cooling','land_abundant','fiber_investment_needed'],
    signals:[
      {type:'interconnection_request',date:'2024-06-12',desc:'Grant County PUD files 1,000MW hydro capacity expansion on mid-Columbia',confidence:'high'},
      {type:'news',date:'2025-03-10',desc:'Fiber consortium announces $200M I-90 route to George/Mattawa',confidence:'medium'},
    ]},
  { id:'quincy-wa', name:'Quincy, WA — Grant County PUD', lat:47.2343, lng:-119.8526,
    type:'existing_dc', status:'operational', powerCapacityMW:1200, powerAvailableMW:200, landAcres:100,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:74,
    region:'northwest', country:'US', state:'WA', city:'Quincy',
    powerCostPerMWh:28, pueEstimate:1.28,
    notes:'Microsoft, Google, Dell, Intuit all present. Grant County PUD hydro = cheapest US power. Nearly land-locked. Best play: acquire existing campuses.',
    tags:['cheapest_power','microsoft_campus','google_campus','acquisition_target','land_constrained'],
    signals:[
      {type:'news',date:'2025-01-20',desc:'Microsoft Quincy adds 400MW expansion — campus now 800MW+',confidence:'high'},
    ]},
  { id:'umatilla-or', name:'Umatilla / Boardman, OR', lat:45.9157, lng:-119.3412,
    type:'greenfield', status:'under_construction', powerCapacityMW:1000, powerAvailableMW:600, landAcres:3000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:83,
    region:'northwest', country:'US', state:'OR', city:'Umatilla',
    powerCostPerMWh:35, pueEstimate:1.32,
    notes:'Amazon (massive Umatilla campus), Boardman DC, others. PacifiCorp + BPA hydro. Columbia River water. Oregon enterprise zone = 15-year property tax exemption. Land $30k–$100k/acre.',
    tags:['amazon_campus','bpa_hydro_power','water_abundant','free_cooling','tax_incentives'],
    signals:[
      {type:'building_permit',date:'2024-04-22',desc:'Amazon Umatilla Phase 6 — 300MW expansion permit',confidence:'high'},
    ]},
  { id:'phoenix-mesa-az', name:'Phoenix / Mesa / Chandler, AZ', lat:33.4152, lng:-111.8315,
    type:'existing_dc', status:'operational', powerCapacityMW:2500, powerAvailableMW:500, landAcres:800,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:83,
    region:'mountain', country:'US', state:'AZ', city:'Mesa',
    powerCostPerMWh:56, pueEstimate:1.45,
    notes:'4th largest US DC market. APS and SRP dual-utility = grid redundancy. Apple, Microsoft, PayPal, Cologix, EdgeConneX all major presences. Water CRITICAL constraint. Land $200k–$600k/acre.',
    tags:['tier2_market','aps_srp_dual_utility','water_scarcity_risk','tax_incentives'],
    signals:[
      {type:'building_permit',date:'2024-12-18',desc:'EdgeConneX Mesa Phase 3 — 250MW permit filed',confidence:'high'},
    ]},
  { id:'goodyear-az', name:'Phoenix / Goodyear (West Valley), AZ', lat:33.4353, lng:-112.3576,
    type:'greenfield', status:'available', powerCapacityMW:800, powerAvailableMW:700, landAcres:5000,
    fiberAccess:'single', waterAccess:'limited', opportunityScore:82,
    region:'mountain', country:'US', state:'AZ', city:'Goodyear',
    powerCostPerMWh:54, pueEstimate:1.45,
    notes:'West Valley — less saturated than East Valley. APS territory. Land $80k–$200k/acre. Loop 303 tech corridor. Amazon recently acquired large West Valley parcels.',
    tags:['aps_power','land_available','tax_incentives','water_scarcity_risk'],
    signals:[
      {type:'land_sale',date:'2024-08-25',desc:'Undisclosed hyperscaler acquires 800 acres Goodyear I-10 corridor',confidence:'medium'},
    ]},

  // ══ INDUSTRIAL CONVERSIONS ════════════════════════════════════════
  { id:'navajo-gs-az', name:'Navajo Generating Station Site, AZ', lat:36.9127, lng:-111.3826,
    type:'industrial_conversion', status:'available', powerCapacityMW:750, powerAvailableMW:700, landAcres:3450,
    fiberAccess:'none', waterAccess:'limited', opportunityScore:64,
    region:'mountain', country:'US', state:'AZ', city:'Page',
    powerCostPerMWh:40, pueEstimate:1.4,
    notes:'Former 2,250MW coal plant (closed 2019). Existing 500kV switchyard intact. SRP/APS transmission lines on-site. 3,450 acres. Navajo Nation land — requires tribal partnership (NTEC). Remote — fiber build significant investment. Transformative if executed.',
    tags:['industrial_conversion','existing_transmission','tribal_partnership_required','remote','coal_to_dc'],
    signals:[
      {type:'partner_announcement',date:'2024-09-15',desc:'Navajo Nation council votes to pursue DC development partnerships on NGS site',confidence:'high'},
    ]},
  { id:'homer-city-pa', name:'Homer City Generation, PA', lat:40.5351, lng:-79.1609,
    type:'industrial_conversion', status:'available', powerCapacityMW:600, powerAvailableMW:550, landAcres:1100,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:77,
    region:'northeast', country:'US', state:'PA', city:'Homer City',
    powerCostPerMWh:48, pueEstimate:1.38,
    notes:'Former 1,884MW coal plant. Existing 345kV transmission direct to PJM backbone. 1,100 acres. Two Lick Creek cooling water. 60 miles from Pittsburgh. Existing substation infrastructure — PJM queue position potentially inherited.',
    tags:['industrial_conversion','pjm_transmission','existing_substation','water_abundant','coal_to_dc'],
    signals:[
      {type:'interconnection_request',date:'2024-10-22',desc:'PJM filing for 400MW power load at Homer City transmission point',confidence:'medium'},
    ]},
  { id:'brayton-point-ma', name:'Brayton Point, Somerset, MA', lat:41.7113, lng:-71.1797,
    type:'industrial_conversion', status:'in_permitting', powerCapacityMW:400, powerAvailableMW:350, landAcres:240,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:72,
    region:'northeast', country:'US', state:'MA', city:'Somerset',
    powerCostPerMWh:70, pueEstimate:1.45,
    notes:'Former 1,535MW coal plant on Mount Hope Bay. ISO-NE transmission connection. Ocean cooling access. Being redeveloped as offshore wind cable landing + DC hub. Wind farm connection = renewable power at competitive rates.',
    tags:['industrial_conversion','offshore_wind_adjacent','ocean_cooling','iso_ne','coal_to_dc'],
    signals:[
      {type:'news',date:'2025-01-30',desc:'MA DPU approves Brayton Point data center zoning variance',confidence:'high'},
    ]},
  { id:'killen-oh', name:'Killen/Stuart Station, OH', lat:38.7284, lng:-83.9749,
    type:'industrial_conversion', status:'available', powerCapacityMW:800, powerAvailableMW:700, landAcres:1800,
    fiberAccess:'none', waterAccess:'abundant', opportunityScore:70,
    region:'midwest', country:'US', state:'OH', city:'Manchester',
    powerCostPerMWh:44, pueEstimate:1.38,
    notes:'Former AEP Ohio coal plants. Ohio River cooling water. 765kV transmission infrastructure — rare and valuable. 1,800 combined acres. Fiber build required. Extraordinary transmission asset for AI compute workloads.',
    tags:['industrial_conversion','765kv_transmission','ohio_river_cooling','coal_to_dc','fiber_investment_needed'],
    signals:[
      {type:'interconnection_request',date:'2025-02-12',desc:'Undisclosed DC developer files PJM load interconnection at Killen 765kV point',confidence:'medium'},
    ]},

  // ══ CANADA ════════════════════════════════════════════════════════
  { id:'montreal-qc', name:'Montreal / Vaudreuil-Dorion, QC, Canada', lat:45.4082, lng:-74.0299,
    type:'greenfield', status:'available', powerCapacityMW:1000, powerAvailableMW:800, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:87,
    region:'canada', country:'CA', state:'QC', city:'Vaudreuil-Dorion',
    powerCostPerMWh:30, pueEstimate:1.25,
    notes:'Hydro-Quebec — virtually unlimited renewable hydro at $0.03/kWh (industrial large-power rate). Among cheapest and cleanest power in North America. Cold climate = free cooling 9+ months. St. Lawrence River water. Fiber via Montreal-NYC routes. Political stability. EXCEPTIONAL power cost case.',
    tags:['hydro_quebec','cheapest_north_american_power','100pct_renewable','free_cooling','water_abundant'],
    signals:[
      {type:'partner_announcement',date:'2024-06-28',desc:"Hydro-Quebec launches 'Cloud Computing Power Rate' — $0.03/kWh, 300MW+ available",confidence:'high'},
      {type:'news',date:'2025-01-15',desc:'Switch and Equinix both exploring Montreal greenfield sites',confidence:'medium'},
    ]},
  { id:'toronto-on', name:'Toronto / Markham, ON, Canada', lat:43.8554, lng:-79.3370,
    type:'existing_dc', status:'operational', powerCapacityMW:500, powerAvailableMW:200, landAcres:200,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:79,
    region:'canada', country:'CA', state:'ON', city:'Markham',
    powerCostPerMWh:65, pueEstimate:1.42,
    notes:'Hydro One + Toronto Hydro territory. Rogers/Bell/Telus fiber hub. Lake Ontario cooling. Cologix, Allied REIT present. Canadian data sovereignty = strong demand driver. Financial services demand dominant.',
    tags:['hydro_one','data_sovereignty','lake_ontario_cooling','financial_services','cologix_present'],
    signals:[
      {type:'news',date:'2024-10-08',desc:'Equinix TR4 Toronto campus announced — $200M 40MW expansion',confidence:'high'},
    ]},
  { id:'vancouver-bc', name:'Vancouver / Surrey, BC, Canada', lat:49.1913, lng:-122.8490,
    type:'greenfield', status:'available', powerCapacityMW:600, powerAvailableMW:500, landAcres:800,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:83,
    region:'canada', country:'CA', state:'BC', city:'Surrey',
    powerCostPerMWh:35, pueEstimate:1.28,
    notes:'BC Hydro power at $0.035-0.05/kWh industrial — primarily hydro. Fraser River water. Pacific rim subsea cables (FASTER, TGN-Pacific). Climate ideal — mild, cool. Surrey/Langley DC corridor developing. BC data privacy laws = sovereignty advantage.',
    tags:['bc_hydro','renewable_hydro','pacific_subsea_cables','water_abundant','free_cooling','data_sovereignty'],
    signals:[
      {type:'news',date:'2024-12-05',desc:"BC Hydro launches 'Digital Economy Power Rate' for large data center loads",confidence:'high'},
    ]},

  // ══ EUROPE ════════════════════════════════════════════════════════
  { id:'zeewolde-nl', name:'Zeewolde / Flevoland, Netherlands', lat:52.3722, lng:5.5414,
    type:'greenfield', status:'under_construction', powerCapacityMW:1200, powerAvailableMW:600, landAcres:740,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:88,
    region:'europe', country:'NL', state:'Flevoland', city:'Zeewolde',
    powerCostPerMWh:60, pueEstimate:1.3,
    notes:'Meta 1.76GW campus approved. Adjacent polder land available. Wind farm proximity = near 100% renewable PPA. AMS-IX fiber hub 40km away. IJmeer water cooling. Schiphol 50km.',
    tags:['meta_campus','wind_renewable','ams_ix_proximity','eu_dc_friendly','water_abundant'],
    signals:[
      {type:'building_permit',date:'2024-08-14',desc:'Meta Zeewolde Phase 1 construction permit approved — 300MW',confidence:'high'},
    ]},
  { id:'dublin-ie', name:'Dublin / South Dublin, Ireland', lat:53.2879, lng:-6.3668,
    type:'existing_dc', status:'operational', powerCapacityMW:1100, powerAvailableMW:100, landAcres:100,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:70,
    region:'europe', country:'IE', state:'Leinster', city:'Dublin',
    powerCostPerMWh:85, pueEstimate:1.4,
    notes:'EU 2nd largest DC market. EirGrid MORATORIUM on new connections in Dublin. Best play: acquire existing licensed facilities. 12.5% corporate tax rate.',
    tags:['grid_constrained','grid_moratorium','acquisition_target','eu_tax_advantage'],
    signals:[
      {type:'news',date:'2024-09-18',desc:'EirGrid announces 2028 target for Dublin grid constraint resolution',confidence:'high'},
    ]},
  { id:'athenry-ie', name:'Athenry, Co. Galway, Ireland', lat:53.3022, lng:-8.7467,
    type:'greenfield', status:'available', powerCapacityMW:300, powerAvailableMW:280, landAcres:590,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:79,
    region:'europe', country:'IE', state:'Connacht', city:'Athenry',
    powerCostPerMWh:70, pueEstimate:1.35,
    notes:'Apple\'s 590-acre site — planning permission CLEARED after 5-year battle. Apple chose not to build. IDA-supported. Wind farm adjacent for renewable PPA. Shovel-ready EU site.',
    tags:['ida_supported','permitted_ready','wind_renewable','apple_cleared_planning'],
    signals:[
      {type:'zoning_change',date:'2024-03-15',desc:'Athenry 590-acre DC site granted 10-year planning permission renewal',confidence:'high'},
    ]},
  { id:'frankfurt-de', name:'Frankfurt Rhine-Main, Germany', lat:50.1109, lng:8.6821,
    type:'existing_dc', status:'operational', powerCapacityMW:2000, powerAvailableMW:300, landAcres:80,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:82,
    region:'europe', country:'DE', state:'Hesse', city:'Frankfurt',
    powerCostPerMWh:85, pueEstimate:1.42,
    notes:'DE-CIX (world\'s largest internet exchange by traffic). Europe\'s #1 DC market. Equinix FR1-FR7, Digital Realty, NTT all massive presences. Land very scarce — premium acquisitions only.',
    tags:['de_cix_hub','tier1_eu_market','land_constrained','acquisition_target','premium_fiber'],
    signals:[
      {type:'news',date:'2024-12-10',desc:'Equinix FR8 campus announced — €1.5B investment in new Frankfurt 300MW facility',confidence:'high'},
    ]},
  { id:'magdeburg-de', name:'Magdeburg, Saxony-Anhalt, Germany', lat:52.1205, lng:11.6276,
    type:'greenfield', status:'announced', powerCapacityMW:2000, powerAvailableMW:1500, landAcres:2500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:86,
    region:'europe', country:'DE', state:'Saxony-Anhalt', city:'Magdeburg',
    powerCostPerMWh:65, pueEstimate:1.32,
    notes:'Intel €17B fab = massive grid upgrade (5GW+). German government €6.8B chip subsidy backstops infrastructure. Elbe River. Land €100k–€300k/ha. EXCEPTIONAL emerging EU market.',
    tags:['intel_fab_adjacent','grid_upgrade','government_subsidy','wind_renewable','emerging_eu_market'],
    signals:[
      {type:'news',date:'2024-05-20',desc:'Intel Magdeburg groundbreaking — €17B fab construction begins',confidence:'high'},
      {type:'land_sale',date:'2025-01-25',desc:'Three hyperscalers acquire combined 1,500 acres adjacent to Intel site',confidence:'medium'},
    ]},
  { id:'eskilstuna-se', name:'Eskilstuna / Mälardalen, Sweden', lat:59.3711, lng:16.5099,
    type:'greenfield', status:'available', powerCapacityMW:1000, powerAvailableMW:900, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:86,
    region:'europe', country:'SE', state:'Södermanland', city:'Eskilstuna',
    powerCostPerMWh:30, pueEstimate:1.22,
    notes:'Vattenfall hydro/wind = near-100% renewable at <€0.030/kWh. Mälaren lake water cooling. Stockholm 100km. Climate = free cooling 10+ months. Land €40k–€150k/acre. Nordic DC policy framework excellent.',
    tags:['cheapest_eu_power','100pct_renewable','free_cooling','nordic_climate','water_abundant'],
    signals:[
      {type:'interconnection_request',date:'2024-07-30',desc:'Svenska kraftnät 800MW transmission upgrade Mälardalen corridor',confidence:'high'},
    ]},
  { id:'kouvola-fi', name:'Helsinki Area / Kouvola, Finland', lat:60.8680, lng:26.7042,
    type:'greenfield', status:'available', powerCapacityMW:600, powerAvailableMW:550, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:84,
    region:'europe', country:'FI', state:'South Karelia', city:'Kouvola',
    powerCostPerMWh:35, pueEstimate:1.25,
    notes:'Finland: 98% renewable electricity + nuclear. Fortum/Statkraft. Vuoksi River + Baltic Sea water cooling. Near-Arctic climate = PUE 1.1-1.2 achievable. Google has massive Hamina Finland campus nearby.',
    tags:['100pct_renewable','arctic_climate_cooling','lowest_eu_pue','fortum_power','water_abundant'],
    signals:[
      {type:'news',date:'2024-09-10',desc:'Google announces 600MW Hamina Finland campus expansion',confidence:'high'},
    ]},
  { id:'reykjavik-is', name:'Reykjavik / Reykjanes, Iceland', lat:63.9854, lng:-22.5560,
    type:'greenfield', status:'available', powerCapacityMW:500, powerAvailableMW:450, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:82,
    region:'europe', country:'IS', state:'Suðurnes', city:'Keflavik',
    powerCostPerMWh:28, pueEstimate:1.15,
    notes:'100% geothermal/hydro = perfectly renewable. HS Orka geothermal. Farice & Danice subsea cables to EU/US. Near-freezing temps = lowest PUE in world (1.1-1.15). Ocean cooling. Best in world for PUE.',
    tags:['100pct_renewable','geothermal_power','lowest_pue_globally','cheapest_power','ocean_cooling'],
    signals:[
      {type:'news',date:'2024-06-25',desc:'Verne Global raises $200M for Keflavik DC expansion — 50MW Phase 3',confidence:'high'},
    ]},
  { id:'sines-pt', name:'Sines, Portugal — Atlantic Hub', lat:37.9566, lng:-8.8650,
    type:'greenfield', status:'available', powerCapacityMW:500, powerAvailableMW:400, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:79,
    region:'europe', country:'PT', state:'Setúbal', city:'Sines',
    powerCostPerMWh:45, pueEstimate:1.35,
    notes:'Portugal: 60%+ renewable grid. Atlantic deep-water port = subsea cable hub (MAREA, EllaLink, 2Africa cables land here). EC declares Sines of European strategic interest for data. Mild Atlantic climate.',
    tags:['subsea_cable_hub','renewable_grid','transatlantic_cables','eu_strategic_interest'],
    signals:[
      {type:'partner_announcement',date:'2024-08-22',desc:'Portugal government designates Sines as national DC strategic hub — €1B incentive',confidence:'high'},
    ]},
  { id:'milan-it', name:'Milan / Siziano, Italy', lat:45.2136, lng:9.2040,
    type:'existing_dc', status:'operational', powerCapacityMW:400, powerAvailableMW:150, landAcres:100,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:78,
    region:'europe', country:'IT', state:'Lombardy', city:'Siziano',
    powerCostPerMWh:90, pueEstimate:1.42,
    notes:"Italy's largest DC market. MIX (Milan Internet Exchange). Digital Realty, Equinix, NTT all present. Po River water cooling. Italian data residency requirements = strong demand. Siziano/Cornaredo industrial zone best for new builds.",
    tags:['mix_hub','eu_data_residency','acquisition_target','po_river_cooling'],
    signals:[
      {type:'news',date:'2024-11-15',desc:'Digital Realty MIL12 Milan campus — €500M announced',confidence:'high'},
    ]},
  { id:'warsaw-pl', name:'Warsaw / Łódź Corridor, Poland', lat:51.7592, lng:19.4560,
    type:'greenfield', status:'emerging', powerCapacityMW:600, powerAvailableMW:500, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:78,
    region:'europe', country:'PL', state:'Łódź Voivodeship', city:'Łódź',
    powerCostPerMWh:65, pueEstimate:1.4,
    notes:'Central EU location. Lower land/labor costs than Western Europe. EU structural funds available. Microsoft and Google both announced Polish expansions.',
    tags:['eu_structural_funds','lower_cost_eu','microsoft_announced','google_announced'],
    signals:[
      {type:'news',date:'2024-08-12',desc:'Microsoft announces $1B Polish cloud region — Warsaw DC campus',confidence:'high'},
    ]},
  { id:'bucharest-ro', name:'Bucharest / Ilfov, Romania', lat:44.4904, lng:26.2136,
    type:'greenfield', status:'emerging', powerCapacityMW:300, powerAvailableMW:250, landAcres:500,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:74,
    region:'europe', country:'RO', state:'Ilfov', city:'Bucharest',
    powerCostPerMWh:65, pueEstimate:1.45,
    notes:'Fastest-growing Central EU DC market. Transelectrica grid. ROTIX (Romania Internet Exchange). Lower labor/land costs than Western Europe. EU structural funds. Microsoft announced €1B Romania investment.',
    tags:['eu_structural_funds','central_eu_emerging','rotix_exchange','microsoft_announced'],
    signals:[
      {type:'news',date:'2024-07-25',desc:'Microsoft announces €1B Romania investment — Azure region, Bucharest campus',confidence:'high'},
    ]},

  // ══ ASIA-PACIFIC ══════════════════════════════════════════════════
  { id:'johor-my', name:'Johor Bahru / Iskandar, Malaysia', lat:1.4927, lng:103.7414,
    type:'greenfield', status:'under_construction', powerCapacityMW:3000, powerAvailableMW:2000, landAcres:5000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:89,
    region:'apac', country:'MY', state:'Johor', city:'Johor Bahru',
    powerCostPerMWh:40, pueEstimate:1.45,
    notes:'HOTTEST APAC market 2024-2025. All hyperscalers building. YTL Power, Microsoft, Google, ByteDance, Equinix all committed. Singapore overflow. TNB investing massively. Land $50k–$300k USD/acre.',
    tags:['hottest_apac','singapore_overflow','tnb_power','tax_incentives','all_hyperscalers'],
    signals:[
      {type:'partner_announcement',date:'2024-04-18',desc:'YTL Power + Microsoft 500MW campus — largest Malaysia DC deal',confidence:'high'},
      {type:'news',date:'2024-11-22',desc:'Equinix JB1 Johor campus opens — 60MW, 5 further phases planned',confidence:'high'},
      {type:'land_sale',date:'2025-01-30',desc:'ByteDance acquires 400 acres Johor for AI DC campus',confidence:'high'},
    ]},
  { id:'batam-id', name:'Batam, Indonesia — Singapore Overflow', lat:1.1301, lng:104.0529,
    type:'greenfield', status:'emerging', powerCapacityMW:800, powerAvailableMW:700, landAcres:3000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:82,
    region:'apac', country:'ID', state:'Riau Islands', city:'Batam',
    powerCostPerMWh:50, pueEstimate:1.55,
    notes:'40km from Singapore (20-min ferry). Free Trade Zone = tax incentives. Singapore hyperscaler overflow at 1/3 the cost. Fiber on JADE/Jaka2LaDeMa cables. Land $20k–$80k USD/acre.',
    tags:['singapore_overflow','free_trade_zone','tax_incentives','stt_gdc_present'],
    signals:[
      {type:'news',date:'2024-10-20',desc:'STT GDC announces 300MW Batam campus — targeting Singapore overflow demand',confidence:'high'},
    ]},
  { id:'navi-mumbai-in', name:'Navi Mumbai / Pune Corridor, India', lat:19.0330, lng:73.0297,
    type:'greenfield', status:'under_construction', powerCapacityMW:1500, powerAvailableMW:1000, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:80,
    region:'apac', country:'IN', state:'Maharashtra', city:'Navi Mumbai',
    powerCostPerMWh:60, pueEstimate:1.5,
    notes:"India's largest DC market. Yotta, Hiranandani, NTT, CtrlS, ST Telemedia all building. Mumbai PoP for subsea cables. 1.4B population driving massive cloud demand.",
    tags:['india_largest_market','subsea_cable_hub','fast_growing_demand','ntt_present'],
    signals:[
      {type:'news',date:'2024-12-05',desc:'AWS announces $12.7B India DC investment through 2030',confidence:'high'},
    ]},
  { id:'inzai-jp', name:'Inzai / Chiba — Tokyo Metro, Japan', lat:35.7209, lng:140.1464,
    type:'greenfield', status:'under_construction', powerCapacityMW:1000, powerAvailableMW:500, landAcres:500,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:79,
    region:'apac', country:'JP', state:'Chiba', city:'Inzai',
    powerCostPerMWh:90, pueEstimate:1.45,
    notes:'Japan DC market growing dramatically. TEPCO. NTT, Equinix, Digital Realty, IIJ all major Chiba/Inzai campuses. METI government incentives. Seismic design premium.',
    tags:['japan_localization_law','tepco_power','ntt_equinix_present','seismic_design_required','meti_incentives'],
    signals:[
      {type:'news',date:'2024-10-15',desc:'METI announces ¥750B Japan DC investment incentive program',confidence:'high'},
    ]},
  { id:'hanam-kr', name:'Seoul / Hanam, South Korea', lat:37.5389, lng:127.2098,
    type:'greenfield', status:'under_construction', powerCapacityMW:600, powerAvailableMW:300, landAcres:300,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:79,
    region:'apac', country:'KR', state:'Gyeonggi', city:'Hanam',
    powerCostPerMWh:80, pueEstimate:1.45,
    notes:'Korea DC market growing rapidly (data localization laws 2023). KEPCO power. Han River water cooling. Equinix, Lumen, KT all present. Samsung, LG enterprise demand + gaming/streaming giants.',
    tags:['kepco_power','data_localization_law','han_river_cooling','equinix_present'],
    signals:[
      {type:'news',date:'2024-11-08',desc:'AWS announces Seoul Region 5th AZ — 400MW+ expansion',confidence:'high'},
    ]},
  { id:'sydney-au', name:'Sydney / Eastern Creek, NSW, Australia', lat:-33.8158, lng:150.8647,
    type:'greenfield', status:'available', powerCapacityMW:600, powerAvailableMW:400, landAcres:600,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:79,
    region:'apac', country:'AU', state:'NSW', city:'Eastern Creek',
    powerCostPerMWh:80, pueEstimate:1.42,
    notes:'AUS market growing fast. Endeavour Energy territory. M7 motorway corridor. Data sovereignty laws = strong local demand. Badgerys Creek airport development creates infrastructure.',
    tags:['australia_largest_market','data_sovereignty_law','airport_adjacent','endeavour_energy'],
    signals:[
      {type:'news',date:'2024-11-20',desc:'Microsoft announces 5-year $5B Australia DC investment program',confidence:'high'},
    ]},
  { id:'bangkok-th', name:'Bangkok / Eastern Seaboard (EEC), Thailand', lat:13.1000, lng:101.0000,
    type:'greenfield', status:'emerging', powerCapacityMW:300, powerAvailableMW:250, landAcres:1000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:74,
    region:'apac', country:'TH', state:'Chonburi', city:'Chonburi (EEC)',
    powerCostPerMWh:70, pueEstimate:1.55,
    notes:'Thailand Eastern Economic Corridor (EEC) = government-backed tech zone. EGAT investing. AWS, Alibaba, Huawei all built Bangkok presence. ASEAN neutrality = safe haven from Johor constraints.',
    tags:['eec_zone','asean_hub','flooding_risk','aws_alibaba_present'],
    signals:[
      {type:'news',date:'2024-09-05',desc:'Google announces first Thailand cloud region — 100MW Bangkok area campus',confidence:'high'},
    ]},
  { id:'hcmc-vn', name:'Ho Chi Minh City, Vietnam', lat:10.8417, lng:106.7750,
    type:'greenfield', status:'emerging', powerCapacityMW:200, powerAvailableMW:180, landAcres:500,
    fiberAccess:'single', waterAccess:'limited', opportunityScore:72,
    region:'apac', country:'VN', state:'Ho Chi Minh City', city:'Thu Duc',
    powerCostPerMWh:60, pueEstimate:1.55,
    notes:'Vietnam growing 7%+/year GDP. FPT, VNPT, CMC major DC operators. Government mandating data localization (Decree 13/2023). Manufacturing boom = enterprise demand.',
    tags:['fastest_growing_apac','data_localization_law','manufacturing_boom','fpt_vnpt_present'],
    signals:[
      {type:'news',date:'2025-01-25',desc:'Microsoft announces Vietnam cloud region — first Ho Chi Minh City campus',confidence:'high'},
    ]},

  // ══ LATIN AMERICA ═════════════════════════════════════════════════
  { id:'sao-paulo-br', name:'São Paulo / Barueri-Cajamar, Brazil', lat:-23.5089, lng:-46.8338,
    type:'greenfield', status:'under_construction', powerCapacityMW:800, powerAvailableMW:500, landAcres:800,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:78,
    region:'latam', country:'BR', state:'São Paulo', city:'Cajamar',
    powerCostPerMWh:75, pueEstimate:1.5,
    notes:"LatAm's largest DC market (80% of Brazil traffic). Equinix SP1-SP5, Ascenty (Digital Bridge) present. LGPD data localization law = strong local demand. Tamboré/Barueri industrial zone best.",
    tags:['latam_largest_market','lgpd_localization','renewable_hydro_ppa','equinix_ascenty_present'],
    signals:[
      {type:'news',date:'2024-08-30',desc:'Ascenty announces 200MW São Paulo campus expansion — Digital Bridge backed',confidence:'high'},
    ]},
  { id:'santiago-chile', name:'Santiago / Lampa, Chile', lat:-33.2774, lng:-70.8805,
    type:'greenfield', status:'available', powerCapacityMW:400, powerAvailableMW:350, landAcres:1000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:80,
    region:'latam', country:'CL', state:'Región Metropolitana', city:'Lampa',
    powerCostPerMWh:55, pueEstimate:1.38,
    notes:'Most politically stable LatAm market. Atacama solar = cheapest renewable in Americas via PPA ($0.020-0.030/kWh). Most stable LatAm country. Seismic Zone 3 design required. NAP Chile subsea cable.',
    tags:['cheapest_latam_power','solar_renewable_ppa','most_stable_latam','seismic_zone'],
    signals:[
      {type:'news',date:'2024-09-10',desc:'Google opens Chile cloud region — Santiago anchor DC campus',confidence:'high'},
    ]},
  { id:'queretaro-mx', name:'Querétaro, Mexico', lat:20.6321, lng:-100.0838,
    type:'greenfield', status:'under_construction', powerCapacityMW:500, powerAvailableMW:400, landAcres:1500,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:76,
    region:'latam', country:'MX', state:'Querétaro', city:'Querétaro',
    powerCostPerMWh:55, pueEstimate:1.45,
    notes:"Mexico's fastest-growing DC market. CFE + NEARSHORING boom = power infrastructure investment. AWS, Microsoft, Oracle all building or announced. Fiber on I-Pan (Mexico City-Guadalajara).",
    tags:['nearshoring_boom','aws_announced','microsoft_announced','cfe_power','fastest_growing_latam'],
    signals:[
      {type:'news',date:'2024-06-15',desc:'AWS announces first Mexico region — Querétaro campus, $15B investment',confidence:'high'},
    ]},
  { id:'bogota-co', name:'Bogotá / Cundinamarca, Colombia', lat:4.6534, lng:-74.0836,
    type:'greenfield', status:'emerging', powerCapacityMW:300, powerAvailableMW:250, landAcres:800,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:73,
    region:'latam', country:'CO', state:'Cundinamarca', city:'Bogotá',
    powerCostPerMWh:60, pueEstimate:1.42,
    notes:'Colombia 70%+ renewable electricity (hydro-dominant). Bogotá at 2,600m altitude — natural cooling advantage. Growing e-commerce + fintech demand. Google Cloud announced Colombia region.',
    tags:['renewable_hydro','altitude_cooling','telmex_fiber','emerging_latam'],
    signals:[
      {type:'news',date:'2024-12-10',desc:'Google Cloud announces Colombia region — Bogotá Campus',confidence:'high'},
    ]},

  // ══ MIDDLE EAST / AFRICA ══════════════════════════════════════════
  { id:'dubai-uae', name:'Dubai / DWC & DAFZA, UAE', lat:25.0657, lng:55.1713,
    type:'greenfield', status:'under_construction', powerCapacityMW:800, powerAvailableMW:500, landAcres:1000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:76,
    region:'mena', country:'AE', state:'Dubai', city:'Dubai',
    powerCostPerMWh:55, pueEstimate:1.55,
    notes:'Regional MENA hub. DEWA investing heavily in DC capacity. Zero corporate tax (2023 9% threshold — DCs likely exempt). Fiber hub for India-EU subsea cables (SEA-ME-WE 6). Extreme heat = major cooling OPEX. Desalination water only.',
    tags:['zero_tax','mena_hub','subsea_cable','dewa_power','extreme_heat_risk'],
    signals:[
      {type:'partner_announcement',date:'2025-01-20',desc:'AWS announces UAE region — Dubai & Abu Dhabi multi-campus',confidence:'high'},
    ]},
  { id:'riyadh-sa', name:'Riyadh / NEOM Zone, Saudi Arabia', lat:24.7136, lng:46.6753,
    type:'greenfield', status:'announced', powerCapacityMW:2000, powerAvailableMW:2000, landAcres:10000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:73,
    region:'mena', country:'SA', state:'Riyadh', city:'Riyadh',
    powerCostPerMWh:45, pueEstimate:1.55,
    notes:'Saudi Vision 2030 massive DC investment program. NEOM OXAGON targeting 1GW+ DC park with solar/wind. PIF (sovereign wealth) as partner. Massive scale possible but governance risk real.',
    tags:['vision_2030','pif_backed','solar_renewable','government_subsidized','extreme_heat','political_risk'],
    signals:[
      {type:'partner_announcement',date:'2024-06-12',desc:'Microsoft $5B Saudi DC + AI partnership with PIF',confidence:'high'},
      {type:'building_permit',date:'2025-01-25',desc:'NEOM OXAGON DC park groundbreaking — 500MW Phase 1',confidence:'high'},
    ]},
  { id:'cairo-eg', name:'Cairo / New Administrative Capital, Egypt', lat:30.2500, lng:31.9000,
    type:'greenfield', status:'announced', powerCapacityMW:400, powerAvailableMW:350, landAcres:2000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:67,
    region:'mena', country:'EG', state:'Cairo Governorate', city:'New Administrative Capital',
    powerCostPerMWh:45, pueEstimate:1.55,
    notes:"Egypt's New Administrative Capital = massive government-backed DC infrastructure. ITIDA target: Egypt to become MENA DC hub. Suez Canal = data transit hub (AAE-1, SMW5 cables). Extreme heat. Strategic crossroads.",
    tags:['government_backed','suez_canal_cables','itida_support','extreme_heat','strategic_location'],
    signals:[
      {type:'partner_announcement',date:'2024-07-20',desc:'Microsoft + Egyptian government MOU — 800MW Egypt data center investment',confidence:'high'},
    ]},
  { id:'nairobi-ke', name:'Nairobi / Konza Techno City, Kenya', lat:-1.4500, lng:37.0833,
    type:'greenfield', status:'emerging', powerCapacityMW:200, powerAvailableMW:180, landAcres:1000,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:69,
    region:'mena', country:'KE', state:'Machakos', city:'Konza Techno City',
    powerCostPerMWh:55, pueEstimate:1.48,
    notes:"Konza Techno City — Kenya's government-backed Silicon Savannah hub. SEACOM + TEAMS + EASSy submarine cable landfall via Mombasa. KenGen renewable power (hydro + geothermal). East Africa's largest DC market.",
    tags:['kenya_govt_backed','seacom_cable','geothermal_power','emerging_africa'],
    signals:[
      {type:'news',date:'2025-01-05',desc:'Microsoft announces $1B Kenya data center investment — first East Africa region',confidence:'high'},
    ]},
  { id:'johannesburg-za', name:'Johannesburg / Cape Town, South Africa', lat:-25.9692, lng:28.1203,
    type:'greenfield', status:'emerging', powerCapacityMW:300, powerAvailableMW:250, landAcres:500,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:68,
    region:'mena', country:'ZA', state:'Gauteng', city:'Midrand',
    powerCostPerMWh:70, pueEstimate:1.48,
    notes:"Africa's largest DC market. Teraco, Africa Data Centres, NTT all present. Eskom grid instability = diesel backup CRITICAL. WIOCC/SEACOM fiber. Cape Town secondary market better climate.",
    tags:['africa_largest_market','grid_instability_risk','seacom_cable','diesel_backup_critical','teraco_present'],
    signals:[
      {type:'news',date:'2024-07-25',desc:'AWS announces Cape Town expansion — $15B Africa investment program',confidence:'high'},
    ]},
  { id:'lagos-ng', name:'Lagos / Lekki, Nigeria', lat:6.4281, lng:3.5417,
    type:'greenfield', status:'emerging', powerCapacityMW:150, powerAvailableMW:130, landAcres:300,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:65,
    region:'mena', country:'NG', state:'Lagos State', city:'Lekki',
    powerCostPerMWh:70, pueEstimate:1.55,
    notes:"Africa's most populous city (25M+). ACE + MainOne + Africa Coast to Europe cables land here. MTN, Airtel, Glo telco demand. Grid unreliability = diesel critical CAPEX. Lekki Free Trade Zone incentives. Massive opportunity but high execution risk.",
    tags:['largest_africa_market','grid_instability_risk','lekki_ftz','ace_cable','diesel_backup_critical'],
    signals:[
      {type:'news',date:'2024-11-30',desc:'MainOne (Google-owned) Lagos DC expands — 48MW Phase 3',confidence:'high'},
    ]},
];

// ── New sites (added with owner data) ────────────────────────────────
const NEW_SITES: SiteRow[] = [
  { id:'monarch-wv', name:'Monarch Campus, Moorefield WV', lat:38.9818, lng:-78.9626,
    type:'greenfield', status:'under_construction', powerCapacityMW:3200, powerAvailableMW:3200, landAcres:2000,
    fiberAccess:'single', waterAccess:'limited', opportunityScore:86,
    region:'northeast', country:'US', state:'WV', city:'Moorefield',
    powerCostPerMWh:42, pueEstimate:1.35,
    owner:'American Intelligence Power (AIP)', forSaleProbability:30,
    notes:'3.2 GW mega-campus backed by former US intelligence community officials. Appalachian Power territory — one of cheapest grid rates in eastern US. DoD/IC-focused tenant strategy. Remote location mitigates physical security risk. Hardy County offered major tax incentives. Announced late 2024, breaking ground 2025.',
    tags:['dod_focused','ic_backed','cheapest_appalachian_power','tax_incentives','remote_secure'],
    signals:[
      {type:'building_permit',date:'2024-11-08',desc:'Hardy County WV approves Monarch Campus mega-DC development — 3.2GW planned',confidence:'high'},
      {type:'news',date:'2025-01-15',desc:'American Intelligence Power raises $2.5B for Moorefield WV campus buildout',confidence:'high'},
    ]},

  { id:'stargate-tx', name:'Project Stargate, Abilene TX', lat:32.4487, lng:-99.7331,
    type:'greenfield', status:'under_construction', powerCapacityMW:1200, powerAvailableMW:1000, landAcres:1400,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:93,
    region:'southwest', country:'US', state:'TX', city:'Abilene',
    powerCostPerMWh:38, pueEstimate:1.35,
    owner:'Stargate LLC (OpenAI / SoftBank / Oracle JV)', forSaleProbability:8,
    notes:'$500B committed JV between OpenAI, SoftBank, Oracle. Phase 1: 1.2GW in Abilene. Total plan: 5GW across US. ERCOT grid + wind PPAs = ~$38/MWh blended. Government-aligned (Executive Order backing). Oracle providing cloud infra, OpenAI AI workloads. One of the largest announced DC investments in history.',
    tags:['ai_first','government_backed','500b_committed','ercot_wind','openai_oracle_softbank'],
    signals:[
      {type:'news',date:'2025-01-21',desc:'President Trump announces $500B Stargate AI infrastructure initiative — Abilene TX first campus',confidence:'high'},
      {type:'building_permit',date:'2025-02-10',desc:'Abilene TX issues permits for 1,400-acre Stargate Phase 1 campus',confidence:'high'},
      {type:'interconnection_request',date:'2025-01-28',desc:'ERCOT interconnection filed for 1,200MW Stargate Abilene facility',confidence:'high'},
    ]},

  { id:'xai-memphis', name:'xAI Colossus Supercluster, Memphis TN', lat:35.1495, lng:-90.0490,
    type:'existing_dc', status:'operational', powerCapacityMW:1000, powerAvailableMW:200, landAcres:100,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:82,
    region:'southeast', country:'US', state:'TN', city:'Memphis',
    powerCostPerMWh:55, pueEstimate:1.3,
    owner:'xAI (Elon Musk)', forSaleProbability:5,
    notes:"World's largest GPU cluster. Colossus v1: 100,000 x H100 GPUs (200MW). Scaling to 1M GPUs / 1GW. Located in former Electrolux factory. Memphis Light Gas Water supply. MLGW controversially granted fast-track power. Core xAI training infrastructure — not for sale.",
    tags:['largest_gpu_cluster','grok_ai','xai_core','mlgw_power','repurposed_factory'],
    signals:[
      {type:'news',date:'2024-07-22',desc:'xAI opens Colossus: 100,000 Nvidia H100 GPUs in Memphis — world largest training cluster',confidence:'high'},
      {type:'news',date:'2025-01-10',desc:'xAI announces Colossus Phase 2: scaling to 1M GPUs and 1GW power',confidence:'high'},
    ]},

  { id:'meta-louisiana', name:'Meta Louisiana Mega-Campus, Richland Parish', lat:32.4183, lng:-91.7629,
    type:'greenfield', status:'under_construction', powerCapacityMW:2000, powerAvailableMW:1800, landAcres:4000,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:87,
    region:'southeast', country:'US', state:'LA', city:'Richland Parish',
    powerCostPerMWh:45, pueEstimate:1.38,
    owner:'Meta Platforms', forSaleProbability:5,
    notes:"Meta's largest single DC campus globally. $10B+ investment. Entergy Louisiana partnership for renewable supply. Mississippi River water access. Richland Parish offered $1.2B in tax incentives (PILOT). Purpose-built for Llama AI training at scale.",
    tags:['meta_ai_training','largest_meta_campus','entergy_renewable','mississippi_river_water','pilot_tax'],
    signals:[
      {type:'building_permit',date:'2024-10-01',desc:'Meta breaks ground on 4,000-acre Louisiana AI campus — $10B Phase 1',confidence:'high'},
      {type:'interconnection_request',date:'2024-09-15',desc:'Entergy Louisiana files 2,000MW interconnection for Meta Richland Parish campus',confidence:'high'},
    ]},

  { id:'microsoft-racine', name:'Microsoft AI Campus, Racine WI', lat:42.7261, lng:-87.7828,
    type:'greenfield', status:'under_construction', powerCapacityMW:500, powerAvailableMW:400, landAcres:700,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:81,
    region:'midwest', country:'US', state:'WI', city:'Racine',
    powerCostPerMWh:52, pueEstimate:1.38,
    owner:'Microsoft', forSaleProbability:5,
    notes:'$3.3B Microsoft investment on former Foxconn site. We Energies partnership. Lake Michigan water cooling. Part of broader $80B FY2025 Microsoft global DC spending. Built on failed Foxconn LCD campus — major brownfield-to-DC conversion. State offered $15M in workforce grants.',
    tags:['microsoft_azure','foxconn_brownfield','lake_michigan_cooling','we_energies','ai_campus'],
    signals:[
      {type:'news',date:'2024-05-08',desc:'Microsoft announces $3.3B Racine Wisconsin AI and cloud campus on Foxconn site',confidence:'high'},
      {type:'building_permit',date:'2024-08-15',desc:'Racine County issues permits for 700-acre Microsoft campus Phase 1',confidence:'high'},
    ]},

  { id:'nuclear-berwick-pa', name:'Susquehanna Nuclear DC Campus, Berwick PA', lat:41.0578, lng:-76.2497,
    type:'power_plant', status:'under_construction', powerCapacityMW:960, powerAvailableMW:800, landAcres:300,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:88,
    region:'northeast', country:'US', state:'PA', city:'Berwick',
    powerCostPerMWh:28, pueEstimate:1.3,
    owner:'Amazon Web Services (campus) / Talen Energy (nuclear plant)', forSaleProbability:10,
    notes:'First major nuclear co-location deal. AWS purchased 960MW directly from Susquehanna nuclear plant via Talen Energy agreement. 24/7 carbon-free power at ~$28/MWh — best clean power cost in US. FERC challenged the agreement (grid bypass concerns) but ultimately approved. Template for future nuclear DC co-location.',
    tags:['nuclear_power','24_7_carbon_free','cheapest_clean_power','aws_anchor','ferc_approved','nuclear_colocation'],
    signals:[
      {type:'partner_announcement',date:'2023-03-28',desc:'Talen Energy signs 960MW nuclear power purchase agreement with Amazon AWS',confidence:'high'},
      {type:'news',date:'2024-09-15',desc:'FERC approves Susquehanna-AWS nuclear co-location deal after review',confidence:'high'},
    ]},

  { id:'google-mayes-ok', name:'Google Pryor Creek Campus, Mayes County OK', lat:36.3090, lng:-95.3200,
    type:'existing_dc', status:'operational', powerCapacityMW:400, powerAvailableMW:50, landAcres:800,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:80,
    region:'southwest', country:'US', state:'OK', city:'Pryor',
    powerCostPerMWh:40, pueEstimate:1.35,
    owner:'Google (Alphabet)', forSaleProbability:5,
    notes:"Google's longest-running hyperscale campus outside Virginia. $4B+ invested since 2007. GRDA (Grand River Dam Authority) hydro power. Expanding heavily for AI. MidAmerica Industrial Park. 100% renewable matched. Not for sale.",
    tags:['google_core','grda_hydro','100_renewable','midamerica_industrial_park','ai_expansion'],
    signals:[
      {type:'news',date:'2024-11-12',desc:'Google announces $1B additional Pryor Creek expansion — AI infrastructure push',confidence:'high'},
    ]},

  { id:'talen-nuclear-pa', name:'Cumulus Data / Nuclear Campus, Berks County PA', lat:40.3932, lng:-75.9946,
    type:'power_plant', status:'in_permitting', powerCapacityMW:2500, powerAvailableMW:2000, landAcres:1800,
    fiberAccess:'single', waterAccess:'abundant', opportunityScore:84,
    region:'northeast', country:'US', state:'PA', city:'Pottstown',
    powerCostPerMWh:32, pueEstimate:1.3,
    owner:'Cumulus Data (Talen Energy spinoff)', forSaleProbability:65,
    notes:'Adjacent to Limerick Nuclear Generating Station (2.3GW). Cumulus Data developing 2.5GW nuclear-adjacent DC campus. Talen spun off Cumulus specifically for DC development. Limerick license extended to 2054. Actively seeking anchor tenants and JV partners. High for-sale probability — Talen looking for strategic partner or full sale.',
    tags:['nuclear_adjacent','limerick_ngs','carbon_free','talen_spinoff','seeking_partner','anchor_tenant_needed'],
    signals:[
      {type:'news',date:'2024-06-20',desc:'Cumulus Data files 2,500MW campus development plan adjacent to Limerick nuclear plant',confidence:'high'},
      {type:'land_sale',date:'2024-04-10',desc:'Talen Energy transfers 1,800 acres to Cumulus Data for nuclear campus development',confidence:'high'},
    ]},

  { id:'coreweave-plano', name:'CoreWeave AI Cloud, Plano TX', lat:33.0198, lng:-96.6989,
    type:'existing_dc', status:'operational', powerCapacityMW:300, powerAvailableMW:50, landAcres:80,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:81,
    region:'southwest', country:'US', state:'TX', city:'Plano',
    powerCostPerMWh:48, pueEstimate:1.25,
    owner:'CoreWeave (Nvidia-backed, NYSE: CRWV)', forSaleProbability:20,
    notes:'Largest AI-native cloud provider. $23B+ in Nvidia GPU inventory. 32 data centers across US and Europe. Recently IPO\'d (March 2025). Microsoft $10B+ customer. Expanding rapidly. Plano TX flagship. Not a real estate play — pure GPU-as-a-service. Potential M&A target for hyperscalers.',
    tags:['ai_gpu_cloud','nvidia_backed','ipo_2025','microsoft_customer','gpu_as_a_service','ma_candidate'],
    signals:[
      {type:'news',date:'2025-03-28',desc:'CoreWeave IPO raises $1.5B at $40B valuation — largest tech IPO of 2025',confidence:'high'},
      {type:'sec_filing',date:'2025-01-15',desc:'CoreWeave S-1 filing reveals $23B GPU inventory and $15B revenue backlog',confidence:'high'},
    ]},

  { id:'cipher-odessa', name:'Cipher Mining / AI Conversion, Odessa TX', lat:31.8457, lng:-102.3676,
    type:'industrial_conversion', status:'available', powerCapacityMW:300, powerAvailableMW:300, landAcres:400,
    fiberAccess:'single', waterAccess:'limited', opportunityScore:72,
    region:'southwest', country:'US', state:'TX', city:'Odessa',
    powerCostPerMWh:35, pueEstimate:1.4,
    owner:'Cipher Mining (NASDAQ: CIFR)', forSaleProbability:75,
    notes:'Publicly traded Bitcoin miner pivoting to AI/HPC hosting. 300MW permitted in ERCOT. Cheap Permian Basin power. Actively marketing sites to AI tenants and potential acquirers. Balance sheet under pressure — high probability of sale or JV. ERCOT West zone with strong wind PPA availability.',
    tags:['bitcoin_miner_pivot','ercot_cheap_power','publicly_traded','ai_hpc_conversion','ma_target','permian_basin'],
    signals:[
      {type:'news',date:'2025-02-14',desc:'Cipher Mining announces pivot from Bitcoin to AI/HPC hosting — exploring strategic alternatives',confidence:'high'},
      {type:'sec_filing',date:'2025-03-01',desc:'CIFR 10-K discloses 300MW permitted capacity and AI conversion strategy',confidence:'high'},
    ]},

  { id:'aligned-chandler-az', name:'Aligned Data Centers, Chandler AZ', lat:33.3062, lng:-111.8413,
    type:'greenfield', status:'under_construction', powerCapacityMW:500, powerAvailableMW:300, landAcres:800,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:80,
    region:'southwest', country:'US', state:'AZ', city:'Chandler',
    powerCostPerMWh:55, pueEstimate:1.3,
    owner:'Aligned Data Centers (Macquarie Capital)', forSaleProbability:50,
    notes:'Macquarie Capital-backed colocation operator. Proprietary Delta3 cooling technology (water-efficient). Phoenix/Chandler market = major hyperscaler demand. Strong Microsoft, Meta tenancy. Macquarie typically holds 5-7yr then exits. Realistic sale or IPO candidate 2026-2027.',
    tags:['macquarie_backed','delta3_cooling','water_efficient','chandler_tech_corridor','hyperscaler_tenant'],
    signals:[
      {type:'building_permit',date:'2024-09-20',desc:'Chandler AZ issues 500MW campus permits for Aligned Phase 3 expansion',confidence:'high'},
    ]},

  { id:'novva-utah', name:'Novva Data Centers, West Jordan UT', lat:40.5621, lng:-112.0089,
    type:'greenfield', status:'under_construction', powerCapacityMW:200, powerAvailableMW:150, landAcres:200,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:78,
    region:'mountain', country:'US', state:'UT', city:'West Jordan',
    powerCostPerMWh:45, pueEstimate:1.32,
    owner:'Novva Data Centers (GI Partners)', forSaleProbability:60,
    notes:'GI Partners PE-backed. Salt Lake Valley market growing fast (Oracle, Adobe, eBay HQs nearby). Rocky Mountain cooling advantage. Rocky Mountain Power (Berkshire Hathaway Energy). GI Partners investment horizon suggests potential exit 2025-2027. Actively seeking strategic capital partners.',
    tags:['gi_partners_backed','salt_lake_market','rocky_mountain_cooling','berkshire_power','pe_exit_horizon'],
    signals:[
      {type:'news',date:'2024-08-01',desc:'Novva secures $500M in financing for West Jordan Utah campus expansion',confidence:'high'},
    ]},

  { id:'edgecore-aurora', name:'EdgeCore Digital, Aurora CO', lat:39.7294, lng:-104.8319,
    type:'greenfield', status:'operational', powerCapacityMW:300, powerAvailableMW:80, landAcres:200,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:77,
    region:'mountain', country:'US', state:'CO', city:'Aurora',
    powerCostPerMWh:50, pueEstimate:1.33,
    owner:'EdgeCore Digital (APG / Ontario Teachers\' Pension)', forSaleProbability:45,
    notes:'Dutch pension (APG) and Ontario Teachers co-investment. Denver/Aurora tech market (AWS, Google, Palantir). 100% renewable commitment via Xcel Energy PPAs. Institutional PE owners with long hold horizon but potential for partial stake sale. Strong operational track record.',
    tags:['pension_fund_backed','denver_market','xcel_renewable','apg_otpp','institutional_capital'],
    signals:[
      {type:'news',date:'2024-07-10',desc:'EdgeCore raises $1.1B for Aurora CO and Phoenix expansion — APG leads',confidence:'high'},
    ]},

  { id:'sabey-quincy', name:'Sabey Data Centers, Quincy WA', lat:47.2343, lng:-119.8526,
    type:'existing_dc', status:'operational', powerCapacityMW:200, powerAvailableMW:40, landAcres:150,
    fiberAccess:'multiple', waterAccess:'abundant', opportunityScore:79,
    region:'northwest', country:'US', state:'WA', city:'Quincy',
    powerCostPerMWh:22, pueEstimate:1.28,
    owner:'Sabey Corporation (private, family-owned)', forSaleProbability:55,
    notes:"Cheapest power in continental US via Columbia River hydroelectric ($0.022/kWh). Quincy WA = Grant County PUD. Major co-location campus alongside Microsoft, Amazon, Yahoo. Sabey is private/family-owned — aging ownership structure increases sale probability. Natural air cooling from Columbia Basin climate. Fiber: CenturyLink, Zayo.",
    tags:['cheapest_us_power','columbia_river_hydro','grant_county_pud','natural_air_cooling','family_owned_pe_candidate'],
    signals:[
      {type:'news',date:'2024-10-05',desc:'Sabey announces 200MW Quincy Phase 4 expansion — seeking capital partner',confidence:'medium'},
    ]},

  { id:'iron-mountain-nova', name:'Iron Mountain Data Centers, Northern Virginia', lat:38.9142, lng:-77.2311,
    type:'existing_dc', status:'operational', powerCapacityMW:150, powerAvailableMW:20, landAcres:40,
    fiberAccess:'multiple', waterAccess:'limited', opportunityScore:73,
    region:'northeast', country:'US', state:'VA', city:'Manassas',
    powerCostPerMWh:58, pueEstimate:1.45,
    owner:'Iron Mountain (NYSE: IRM — REIT)', forSaleProbability:60,
    notes:'Iron Mountain is a public REIT with mixed physical archive + DC business. DC segment growing but non-core assets may be divested. NOVA assets well-located but older vintage (2008-2015). REIT structure = pressure to recycle capital. Potential sale-leaseback opportunity. Activist investor interest in pure-play DC REIT spin-off.',
    tags:['public_reit','sale_leaseback_candidate','older_vintage','activist_pressure','non_core_assets'],
    signals:[
      {type:'sec_filing',date:'2025-01-30',desc:'Iron Mountain 10-K highlights DC segment as growth priority — older assets under review',confidence:'medium'},
    ]},
];

// Merge new sites into master list
SITES.push(...NEW_SITES);

// ── Owner / for-sale probability for existing sites ───────────────────
// Applied after insert via UPDATE so we don't need to touch the huge SITES array
const OWNER_DATA: Record<string, { owner: string; prob: number }> = {
  'pwc-va':         { owner: 'QTS/Blackstone, Vantage, Digital Realty, Quantum Loophole (multi-owner zone)', prob: 55 },
  'loudoun-va':     { owner: 'Equinix, Digital Realty, NTT, QTS, CoreSite, Cologix', prob: 20 },
  'new-albany-oh':  { owner: 'Meta Platforms (primary), Amazon AWS', prob: 5 },
  'memphis-tn':     { owner: 'Meta Platforms, Microsoft (DeSoto County zone)', prob: 8 },
  'cheyenne-wy':    { owner: 'Microsoft, Google, Lumen Technologies', prob: 15 },
  'homer-city-pa':  { owner: 'Homer City OL LLC (NRG successor) — site available', prob: 80 },
  'san-antonio-tx': { owner: 'CPS Energy (utility land), multiple colocation operators', prob: 50 },
  'zeewolde-nl':    { owner: 'Microsoft', prob: 8 },
  'frankfurt-de':   { owner: 'Equinix, NTT, CyrusOne/GDS, Digital Realty, Telehouse', prob: 25 },
  'amsterdam-nl':   { owner: 'Equinix, Digital Realty, NTT, Iron Mountain', prob: 20 },
  'london-uk':      { owner: 'Equinix, Ark Data Centres, Virtus, DC Byte, NTT', prob: 25 },
  'madrid-es':      { owner: 'Equinix, Interxion/Digital Realty, Nabiax', prob: 35 },
  'stockholm-se':   { owner: 'Bahnhof, DigiPlex/Vantage, Equinix', prob: 35 },
  'milan-it':       { owner: 'Aruba S.p.A., Equinix, NTT', prob: 40 },
  'paris-fr':       { owner: 'Equinix, Interxion/DRT, Data4 (AXA IM)', prob: 25 },
  'magdeburg-de':   { owner: 'Intel (fab adjacent land), Amazon AWS', prob: 12 },
  'warsaw-pl':      { owner: 'Equinix, Atman (PRTCOM), Beyond.pl', prob: 45 },
  'bucharest-ro':   { owner: 'Telekom Romania, M247, RCSRDS', prob: 60 },
  'singapore-sg':   { owner: 'Equinix, Digital Realty, Keppel DC REIT, NTT', prob: 20 },
  'tokyo-jp':       { owner: 'Equinix, NTT, IIJ, Digital Realty, Colt DCS', prob: 15 },
  'seoul-kr':       { owner: 'KT (Korea Telecom), SKT, LG U+, NAVER', prob: 20 },
  'sydney-au':      { owner: 'Equinix, NTT, Macquarie Data Centres, NEXTDC', prob: 25 },
  'johor-my':       { owner: 'YTL Power International, Bridge Data Centres, AIMS', prob: 30 },
  'mumbai-in':      { owner: 'STT GDC India, CtrlS, NTT, Nxtra (Airtel)', prob: 40 },
  'bangalore-in':   { owner: 'CtrlS, NxtGen, Yotta Infrastructure, GPX India', prob: 45 },
  'hyderabad-in':   { owner: 'Amazon AWS (building), Microsoft, Google (announced)', prob: 10 },
  'jakarta-id':     { owner: 'DCI Indonesia (Salim Group), NTT, Telkom Indonesia', prob: 40 },
  'bangkok-th':     { owner: 'True IDC, Keppel DC, CAT Telecom, AWS (announced)', prob: 45 },
  'hcmc-vn':        { owner: 'Viettel IDC, FPT Telecom, CMC Telecom', prob: 50 },
  'sao-paulo-br':   { owner: 'Equinix, Ascenty (Digital Bridge / Brookfield)', prob: 35 },
  'santiago-chile': { owner: 'Equinix, Entel, GTD Grupo Teleductos', prob: 40 },
  'queretaro-mx':   { owner: 'KIO Networks, Equinix, CyrusOne', prob: 40 },
  'bogota-co':      { owner: 'ETB, Claro Colombia, Equinix (announced)', prob: 45 },
  'dubai-uae':      { owner: 'Khazna Data Centres (DEWA/ADQ), du datamena, Equinix', prob: 30 },
  'riyadh-sa':      { owner: 'STC (Saudi Telecom), Alibaba Cloud, PIF/NEOM', prob: 20 },
  'cairo-eg':       { owner: 'Telecom Egypt, Vodafone Egypt, Orange Egypt', prob: 55 },
  'nairobi-ke':     { owner: 'Safaricom PLC, Rack Centre, East Africa Data Centres', prob: 55 },
  'johannesburg-za':{ owner: 'Teraco (Berkshire Partners), Africa Data Centres (Cassava)', prob: 35 },
  'lagos-ng':       { owner: 'MainOne/Google, Rack Centre, Medallion Communications', prob: 55 },
};

// ── Exported seed function ────────────────────────────────────────────
export function seedDatabase(db: DatabaseSync): { siteCount: number; signalCount: number } {
  const insertSite = db.prepare(`
    INSERT OR REPLACE INTO sites
    (id,name,lat,lng,type,status,power_capacity_mw,power_available_mw,land_acres,
     fiber_access,water_access,opportunity_score,region,country,state,city,
     power_cost_per_mwh,pue_estimate,notes,tags,owner,for_sale_probability)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `);

  const insertSignal = db.prepare(`
    INSERT INTO signals (site_id,type,date,description,confidence)
    VALUES (?,?,?,?,?)
  `);

  let siteCount = 0;
  let signalCount = 0;

  const updateOwner = db.prepare(
    `UPDATE sites SET owner = ?, for_sale_probability = ? WHERE id = ? AND (owner = '' OR owner IS NULL)`
  );

  db.exec('BEGIN');
  try {
    for (const site of SITES) {
      insertSite.run(
        site.id, site.name, site.lat, site.lng, site.type, site.status,
        site.powerCapacityMW, site.powerAvailableMW, site.landAcres,
        site.fiberAccess, site.waterAccess, site.opportunityScore,
        site.region, site.country, site.state || null, site.city,
        site.powerCostPerMWh, site.pueEstimate,
        site.notes, JSON.stringify(site.tags),
        site.owner || '', site.forSaleProbability ?? 50
      );
      siteCount++;
      for (const sig of site.signals) {
        insertSignal.run(site.id, sig.type, sig.date, sig.desc, sig.confidence);
        signalCount++;
      }
    }
    // Apply owner data to existing sites that didn't have it inline
    for (const [id, data] of Object.entries(OWNER_DATA)) {
      updateOwner.run(data.owner, data.prob, id);
    }
    db.exec('COMMIT');
  } catch (e) {
    db.exec('ROLLBACK');
    throw e;
  }

  return { siteCount, signalCount };
}
