export type SiteType = 'greenfield' | 'existing_dc' | 'industrial_conversion' | 'power_plant' | 'partner';
export type SiteStatus = 'available' | 'under_construction' | 'announced' | 'operational' | 'for_sale' | 'in_permitting' | 'emerging';
export type FiberAccess = 'none' | 'single' | 'multiple';
export type WaterAccess = 'none' | 'limited' | 'abundant';
export type SignalType = 'interconnection_request' | 'building_permit' | 'water_permit' | 'zoning_change' | 'news' | 'sec_filing' | 'job_posting' | 'land_sale' | 'satellite_change' | 'power_plant_retirement' | 'partner_announcement';
export type Confidence = 'high' | 'medium' | 'low';
export type Region = 'northeast' | 'southeast' | 'midwest' | 'southwest' | 'mountain' | 'northwest' | 'canada' | 'europe' | 'apac' | 'latam' | 'mena';

export interface Signal {
  id?: number;
  siteId: string;
  type: SignalType;
  date: string;
  description: string;
  sourceUrl?: string;
  confidence: Confidence;
  autoGenerated?: boolean;
  createdAt?: string;
}

export interface Site {
  id: string;
  name: string;
  lat: number;
  lng: number;
  type: SiteType;
  status: SiteStatus;
  powerCapacityMW: number;
  powerAvailableMW: number;
  landAcres: number;
  fiberAccess: FiberAccess;
  waterAccess: WaterAccess;
  opportunityScore: number;
  region: Region;
  country: string;
  state?: string;
  city: string;
  powerCostPerMWh: number;
  pueEstimate: number;
  askingPriceMUSD?: number;
  notes: string;
  tags: string[];
  userNotes?: string;
  watchlisted?: boolean;
  signals?: Signal[];
  lastUpdated?: string;
  createdAt?: string;
}

export interface Company {
  id: string;
  name: string;
  type: string;
  totalCapacityMW: number;
  pipelineMW: number;
  color: string;
  description: string;
  website: string;
}

export interface IngestionRun {
  id?: number;
  script: string;
  status: 'running' | 'completed' | 'failed';
  startedAt: string;
  completedAt?: string;
  signalsFound: number;
  output: string;
}

export interface FilterState {
  search: string;
  region: string;
  type: string;
  status: string;
  country: string;
  minScore: number;
  minPower: number;
  minLand: number;
  maxPowerCost: number;
  watchlistOnly: boolean;
  sort: 'score' | 'power' | 'land' | 'name' | 'cost';
}
